allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
minimumReleaseAgeExclude:
  - '@mui/core-downloads-tracker@9.3.0'
  - '@mui/icons-material@9.3.0'
  - '@mui/material@9.3.0'
  - '@mui/private-theming@9.3.0'
  - '@mui/styled-engine@9.3.0'
  - '@mui/system@9.3.0'
  - '@mui/types@9.3.0'
  - '@mui/utils@9.3.0'
